-- EJERCICIO 1 --
SELECT C.APELLIDOS, C.NOMBRE, C.DNI, C.TELEFONO, V.MATRICULA, MA.MARCA, M.MODELO, VA.FECHA_ACCIDENTE, T.DESCR_ACCID, P.PROVINCIA
FROM SV_CLIENTES C JOIN SV_VEHICULOS V ON C.DNI = V.DNI JOIN SV_MODELOS M ON V.IDMODELO = M.IDMODELO 
JOIN SV_MARCAS MA ON M.IDMARCA = MA.IDMARCA JOIN SV_VEHIC_ACCID VA ON V.MATRICULA = VA.MATRICULA 
JOIN SV_TIPOSACCIDENTES T ON VA.IDACCIDENTE = T.IDACCIDENTE JOIN PROVINCIAS P ON C.IDPROVINCIA = P.IDPROVINCIA
WHERE UPPER(C.SEXO) = 'M' AND VA.FECHA_ACCIDENTE LIKE '%2021' AND UPPER(VA.RESPONSABLE) = 'S' AND UPPER(P.PROVINCIA) ='CIUDAD REAL';
