-- EJERCICIO 2--
SELECT T.DESCR_ACCID, COUNT(DESCR_ACCID) AS "Nº ACCIDENTES"  FROM SV_TIPOSACCIDENTES T JOIN SV_VEHIC_ACCID VA ON T.IDACCIDENTE = VA.IDACCIDENTE
GROUP BY DESCR_ACCID
HAVING COUNT(*)>3
ORDER BY T.DESCR_ACCID DESC;



