-- EJERCICIO 3 --
-- SIN REFERENCIA EXTERNA --
SELECT V.MATRICULA, MA.MARCA, M.MODELO, VA.FECHA_ACCIDENTE, VA.RESPONSABLE
FROM  SV_VEHICULOS V JOIN SV_MODELOS M ON V.IDMODELO = M.IDMODELO 
JOIN SV_MARCAS MA ON M.IDMARCA = MA.IDMARCA JOIN SV_VEHIC_ACCID VA ON V.MATRICULA = VA.MATRICULA
WHERE UPPER(M.MODELO) LIKE '%GT%' AND VA.FECHA_ACCIDENTE BETWEEN TO_DATE('01/03/2019','DD/MM/YYYY') AND TO_DATE ('12/11/2021','DD/MM/YYYY')
AND MA.IDMARCA IN (SELECT M.IDMARCA FROM SV_MODELOS M GROUP BY M.IDMARCA HAVING COUNT(M.IDMARCA)>1);
-- CON REFERENCIA EXTERNA --
